// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdraTfterop6lBtqB240irrjN_-dlCCBY',
    appId: '1:398889858847:web:4ebe59eb8483d1edd2622a',
    messagingSenderId: '398889858847',
    projectId: 'eneo-management-app',
    authDomain: 'eneo-management-app.firebaseapp.com',
    storageBucket: 'eneo-management-app.firebasestorage.app',
    measurementId: 'G-FHCWHX17BE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbKoxAQrWzQU5Hon4i3Mv8e4GNex9QwHM',
    appId: '1:398889858847:android:ce109363b9062d84d2622a',
    messagingSenderId: '398889858847',
    projectId: 'eneo-management-app',
    storageBucket: 'eneo-management-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcwx8ema9XxY_41xkc88bWj2jGzoKdYlM',
    appId: '1:398889858847:ios:802c045352866213d2622a',
    messagingSenderId: '398889858847',
    projectId: 'eneo-management-app',
    storageBucket: 'eneo-management-app.firebasestorage.app',
    iosClientId: '398889858847-ricfoj9urk8kofr6kgpjbrkbckp1n2k6.apps.googleusercontent.com',
    iosBundleId: 'com.example.eneoElectricalTransformerManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcwx8ema9XxY_41xkc88bWj2jGzoKdYlM',
    appId: '1:398889858847:ios:802c045352866213d2622a',
    messagingSenderId: '398889858847',
    projectId: 'eneo-management-app',
    storageBucket: 'eneo-management-app.firebasestorage.app',
    iosClientId: '398889858847-ricfoj9urk8kofr6kgpjbrkbckp1n2k6.apps.googleusercontent.com',
    iosBundleId: 'com.example.eneoElectricalTransformerManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdraTfterop6lBtqB240irrjN_-dlCCBY',
    appId: '1:398889858847:web:4ebe59eb8483d1edd2622a',
    messagingSenderId: '398889858847',
    projectId: 'eneo-management-app',
    authDomain: 'eneo-management-app.firebaseapp.com',
    storageBucket: 'eneo-management-app.firebasestorage.app',
    measurementId: 'G-FHCWHX17BE',
  );
}
